import { del, get } from "@vercel/blob";
import { createReadStream } from "fs";
import { mkdir, unlink, writeFile } from "fs/promises";
import { Readable } from "stream";
import crypto from "crypto";
import os from "os";
import path from "path";

/**
 * Two interchangeable backends behind one interface:
 *  - "blob"  — Vercel Blob, used whenever BLOB_READ_WRITE_TOKEN is set.
 *              Browsers upload straight to Blob (no size limit from our API),
 *              storageKey is the blob URL.
 *  - "local" — dev fallback with zero external services. Files land in
 *              .uploads/, storageKey is "local:<random>".
 */
export type StorageMode = "blob" | "local";

export function storageMode(): StorageMode {
  return process.env.BLOB_READ_WRITE_TOKEN ? "blob" : "local";
}

// Outside the project directory on purpose: Next's dev-mode file watcher
// treats anything written under the project root as a reason to reload,
// which would interrupt an in-progress local upload.
const LOCAL_DIR = path.join(os.tmpdir(), "dataroom-uploads");
const LOCAL_PREFIX = "local:";

export async function saveLocalFile(data: ArrayBuffer): Promise<string> {
  const key = crypto.randomBytes(16).toString("hex");
  await mkdir(LOCAL_DIR, { recursive: true });
  await writeFile(path.join(LOCAL_DIR, key), Buffer.from(data));
  return LOCAL_PREFIX + key;
}

/** Streams a stored object regardless of backend. */
export async function readStoredFile(
  storageKey: string
): Promise<{ stream: ReadableStream; size?: number } | null> {
  if (storageKey.startsWith(LOCAL_PREFIX)) {
    const key = storageKey.slice(LOCAL_PREFIX.length);
    // The key is generated by us (hex), but never trust it as a path.
    if (!/^[0-9a-f]+$/.test(key)) return null;
    try {
      const nodeStream = createReadStream(path.join(LOCAL_DIR, key));
      return { stream: Readable.toWeb(nodeStream) as ReadableStream };
    } catch {
      return null;
    }
  }

  // Blobs are uploaded with access: "private" — the raw URL isn't fetchable
  // without the read-write token, which get() applies for us. We never hand
  // this URL to a client anyway; every download goes through our own
  // access-checked route (see app/api/files/[fileId]/content).
  try {
    const result = await get(storageKey, { access: "private" });
    if (!result?.stream) return null; // null on a 304, which we never trigger
    return { stream: result.stream, size: result.blob.size ?? undefined };
  } catch {
    return null;
  }
}

/** Best-effort cleanup; storage orphans are preferable to broken metadata. */
export async function deleteStoredFiles(storageKeys: string[]) {
  const local = storageKeys.filter((k) => k.startsWith(LOCAL_PREFIX));
  const blobs = storageKeys.filter((k) => !k.startsWith(LOCAL_PREFIX));

  await Promise.allSettled([
    ...local.map((k) => unlink(path.join(LOCAL_DIR, k.slice(LOCAL_PREFIX.length)))),
    blobs.length ? del(blobs) : Promise.resolve(),
  ]);
}
